export const trendingTitles: string[] = [
    "House of the Dragon",
    // "Stree 2",
    // "Anora",
    "Wicked",
    "The Substance",
    "The Mentalist",
    "A Complete Unknown",
    "Lucifer",
    "The Brutalist",
    // "Moana 2",
    "Dog Man",
    "Suits",
    // "Heart Eyes",
    "I want to eat your pancreas",
    // "Vermiglio",
    // "Hazbin Hotel",
    // "Squid Game",
    // "Narcos",
    // "Slow Horses",
    // "La Rosa De Guadalupe"
  ];
  
export const thrillerTitles: string[] = [
    // "From",
    // "The Night Agent",
    // "Black Doves",
    "Dexter",
    "The Crown",
    "Monsters: The Lyle and Erik Menendez Story",
    "Squid Game",
    "Slow Horses",
    "The Boys",
    // "Argylle",
    // "Godzilla Minus One",
    // "Stree 2",
    // "Den of Thieves 2: Pantera",
    "Death Note",
    "The Walking Dead",
    "Anora",
    "The 100",
    // "Vermiglio",
    // "Hazbin Hotel",
    // "La Rosa De Guadalupe"
  ];
  
export const comedyTitles: string[] = [
    // "Hazbin Hotel",
    // "Wonka",
    // "The Big Sick",
    // "Bill & Ted's Excellent Adventure",
    "The Birdcage",
    "Bottoms",
    "Bowfinger",
    "Hundreds of Beavers",
    "Fargo",
    // "Heathers",
    // "The General",
    "Knives Out",
    "My Old Ass",
    "Crazy, Stupid, Love",
    "When Harry Met Sally...",
    // "Hitch",
    // "Superbad",
    "Bridesmaids",
    // "The 40-Year-Old Virgin",
    // "Step Brothers"
  ];
  
export const romanceTitles: string[] = [
    "Bridgerton",
    "La La Land",
    "Pride and Prejudice",
    // "The Notebook",
    // "Portrait of a Lady on Fire",
    // "Roman Holiday",
    // "Notting Hill",
    "Before Sunrise",
    "The Princess Bride",
    // "Sleepless in Seattle",
    // "Eternal Sunshine of the Spotless Mind",
    "10 Things I Hate About You",
    // "500 Days of Summer",
    // "Beauty and the Beast",
    // "The Big Sick",
    "Anyone but you",
    "Brokeback Mountain",
    "When Harry Met Sally...",
    "Casablanca",
    "Moonstruck"
  ];
  